### ISSUE TITLE
publish for Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/csvquery#13]
- [x] https://github.com/skinny-framework/skinny-framework/issues/409 

https://github.com/scalikejdbc/csvquery/blob/35f19983c051d4e3053e0e087f9e24c92562b745/build.sbt#L12-L14

https://github.com/scalikejdbc/csvquery/commit/b0c71ea9d4ff519fe03d0c6e1e6058bea0db76ce

**Comment by seratch** [comment]
done
